apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30091  # Access via minikubeIP:30081
