apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: ecommerce
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9zYXJhbnNoMDUwNjAwOk5ldHNldHRlcmU1QGNsdXN0ZXIwLjlrZXJ4YnUubW9uZ29kYi5uZXQvcHJvZHVjdHM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  JWT_SECRET: eW91cl9zdHJvbmdfc2VjcmV0X2tleQ==
  RABBITMQ_URL: YW1hcHA6Ly9sb2NhbGhvc3Q=
  PORT: NTAwMQ==  # base64 of "5001"
  FRONTEND_URL: aHR0cDovL3VpLXNlcnZpY2U6MzAwMA==  # base64 of "http://ui-service:3000"
