apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30092  # Access via minikubeIP:30081