# auth-DB-mongo-init-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-mongo-init-configmap
data:
  mongo-init.js: |
    db = db.getSiblingDB('ecommerce');
    
    // Create application user
    db.createUser({
      user: 'ecommerce_user',
      pwd: 'secure_password',
      roles: [
        {
          role: 'readWrite',
          db: 'ecommerce',
        },
      ],
    });
    
    // Create initial collections
    db.createCollection('users');
    db.createCollection('sessions');
    
    // Create indexes for better performance
    db.users.createIndex({ email: 1 }, { unique: true });
    db.users.createIndex({ "passwordResetToken": 1, "passwordResetExpires": 1 });