# auth-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: ecommerce
type: Opaque
data:
  jwt-access-secret: eW91cl9zdHJvbmdfc2VjcmV0X2tleQ== # your_strong_secret_key (base64 encoded)
  jwt-refresh-secret: eW91cl9zdHJvbmdfc2VjcmV0X2tleQ== # your_strong_secret_key (base64 encoded)